### ISSUE TITLE
Support ansible >= 2.8

### ISSUE THREAD

**Issue by shalomb** [shalomb/ansible-systemd-timesyncd#3]

**Comment by shalomb** [comment]
```
$ ./tests.yml -l localhost -vv
...
PLAY RECAP **********************************************************************************************************************************************************************localhost                  : ok=20   changed=7    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0                                                                                                                                                                                                                                                Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fadcb98df28>                                                                                  Traceback (most recent call last):                                                                                                                                                 File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fadcb98df28>
Traceback (most recent call last):
File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fadcb98df28>
Traceback (most recent call last):
File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fadcb98df28>
Traceback (most recent call last):
File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fadcb98df28>
Traceback (most recent call last):
File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fadcb98df28>
```

Seems to be caused by https://github.com/ansible/ansible/issues/21982 and sticking with ansible <= 2.8 seems to keep things chugging.
